#!/bin/bash


SRC=$(echo ${PWD} | cut -d "/" -f 4)
echo $SRC

PORT=''
SERVER=''

if [[ "$SRC" == "robot.onyxcherry.pl" || "$SRC" == "arduino.onyxcherry.pl" ]]; then
        PORT='10333'
        SERVER='srv04'
elif [[ "$SRC" == "onyxcherry.pl" ]]; then
        PORT='10261'
        SERVER='srv03'
fi

echo $PORT
echo $SERVER

rsync -avh --progress --delete -e "ssh -p ${PORT} -i /root/.ssh/root@${SERVER}" \
/home/tomasz/${SRC}/public root@${SERVER}.mikr.us:/var/www/html/${SRC}/
